CREATE SCHEMA IF NOT EXISTS BRING_IT AUTHORIZATION SA;

DROP TABLE USERS IF EXISTS CASCADE;

CREATE TABLE users (
  id VARCHAR(255) NOT NULL,
   username VARCHAR(255) NULL,
   email VARCHAR(255) NULL,
   password VARCHAR(255) NULL,
   password_salt VARCHAR(255) NULL,
   CONSTRAINT pk_users PRIMARY KEY (id)
);


DROP TABLE BRINGIT_CORE_LIST IF EXISTS CASCADE;

CREATE TABLE bringit_core_list (
  id VARCHAR(255) NOT NULL,
   owner VARCHAR(255) NULL,
   list_title VARCHAR(255) NULL,
   participants VARCHAR(255) NULL,
   CONSTRAINT pk_bringit_core_list PRIMARY KEY (id)
);

ALTER TABLE bringit_core_list ADD CONSTRAINT FK_BRINGIT_CORE_LIST_ON_OWNER FOREIGN KEY (owner) REFERENCES users (id);
ALTER TABLE bringit_core_list ADD CONSTRAINT FK_BRINGIT_CORE_LIST_ON_PARTICIPANTS FOREIGN KEY (participants)
    REFERENCES PARTICIPANT_REG (id);

DROP TABLE PARTICIPANT_REG IF EXISTS CASCADE;

CREATE TABLE participant_reg (
  id VARCHAR(255) NOT NULL,
   list VARCHAR(255) NULL,
   participant VARCHAR(255) NULL,
   CONSTRAINT pk_participant_reg PRIMARY KEY (id)
);

ALTER TABLE participant_reg ADD CONSTRAINT FK_PARTICIPANT_REG_ON_LIST FOREIGN KEY (list) REFERENCES bringit_core_list (id);
ALTER TABLE participant_reg ADD CONSTRAINT FK_PARTICIPANT_REG_ON_PARTICIPANT FOREIGN KEY (participant) REFERENCES users (id);